name: show-tag
on:
  release:
    types: [published]

jobs:
  show-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "{release_tag}=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.release_tag }}"
